export const CATEGORIES = {
  raptors: {
    label: 'Raptors',
    icon: '🦅',
    color: '#b71c1c',
    subcategories: [
      'Red Kite', 'Common Buzzard', 'Sparrowhawk', 'Kestrel', 'Peregrine', 'Hobby',
      'Marsh Harrier', 'Hen Harrier', 'Montagu\'s Harrier', 'Merlin', 'Osprey',
      'White-tailed Eagle', 'Golden Eagle', 'Red-footed Falcon', 'Other',
    ],
    recipient: 'raptors@bto.org',
  },
  waterfowl: {
    label: 'Waterfowl',
    icon: '🦆',
    color: '#1565c0',
    subcategories: [
      'Mallard', 'Teal', 'Wigeon', 'Gadwall', 'Shoveler', 'Pintail',
      'Pochard', 'Tufted Duck', 'Eider', 'Goldeneye', 'Smew', 'Goosander',
      'Canada Goose', 'Greylag Goose', 'Pink-footed Goose', 'Barnacle Goose', 'Brent Goose',
      'Mute Swan', 'Whooper Swan', 'Bewick\'s Swan',
      'Great Crested Grebe', 'Little Grebe', 'Coot', 'Moorhen', 'Other',
    ],
    recipient: 'waterfowl@bto.org',
  },
  waders: {
    label: 'Waders',
    icon: '🦩',
    color: '#e65100',
    subcategories: [
      'Grey Heron', 'Little Egret', 'Great White Egret', 'Spoonbill',
      'Lapwing', 'Golden Plover', 'Ringed Plover', 'Little Ringed Plover',
      'Oystercatcher', 'Avocet', 'Curlew', 'Whimbrel',
      'Black-tailed Godwit', 'Bar-tailed Godwit',
      'Redshank', 'Greenshank', 'Green Sandpiper', 'Common Sandpiper',
      'Dunlin', 'Knot', 'Sanderling', 'Turnstone',
      'Snipe', 'Jack Snipe', 'Woodcock', 'Other',
    ],
    recipient: 'waders@bto.org',
  },
  seabirds: {
    label: 'Seabirds',
    icon: '🌊',
    color: '#006064',
    subcategories: [
      'Herring Gull', 'Lesser Black-backed Gull', 'Great Black-backed Gull',
      'Black-headed Gull', 'Common Gull', 'Kittiwake', 'Mediterranean Gull',
      'Common Tern', 'Arctic Tern', 'Little Tern', 'Sandwich Tern', 'Roseate Tern',
      'Gannet', 'Cormorant', 'Shag', 'Great Skua', 'Arctic Skua',
      'Puffin', 'Guillemot', 'Razorbill', 'Black Guillemot', 'Little Auk',
      'Fulmar', 'Manx Shearwater', 'Sooty Shearwater', 'Storm Petrel', 'Other',
    ],
    recipient: 'seabirds@bto.org',
  },
  songbirds: {
    label: 'Songbirds',
    icon: '🐦',
    color: '#2e7d32',
    subcategories: [
      'Robin', 'Blackbird', 'Song Thrush', 'Mistle Thrush', 'Fieldfare', 'Redwing',
      'Wren', 'Dunnock', 'Starling',
      'House Sparrow', 'Tree Sparrow',
      'Chaffinch', 'Brambling', 'Goldfinch', 'Greenfinch', 'Siskin',
      'Linnet', 'Redpoll', 'Crossbill', 'Bullfinch', 'Hawfinch',
      'Blue Tit', 'Great Tit', 'Coal Tit', 'Marsh Tit', 'Long-tailed Tit',
      'Blackcap', 'Garden Warbler', 'Whitethroat', 'Lesser Whitethroat',
      'Chiffchaff', 'Willow Warbler', 'Wood Warbler', 'Sedge Warbler', 'Reed Warbler',
      'Swallow', 'House Martin', 'Sand Martin', 'Swift',
      'Spotted Flycatcher', 'Pied Flycatcher',
      'Nuthatch', 'Treecreeper',
      'Great Spotted Woodpecker', 'Green Woodpecker', 'Lesser Spotted Woodpecker',
      'Skylark', 'Meadow Pipit', 'Rock Pipit', 'Grey Wagtail', 'Pied Wagtail',
      'Kingfisher', 'Dipper', 'Grey Partridge', 'Other',
    ],
    recipient: 'songbirds@bto.org',
  },
  owls: {
    label: 'Owls',
    icon: '🦉',
    color: '#4527a0',
    subcategories: [
      'Barn Owl', 'Tawny Owl', 'Little Owl',
      'Short-eared Owl', 'Long-eared Owl', 'Other',
    ],
    recipient: 'owls@bto.org',
  },
  corvids: {
    label: 'Corvids',
    icon: '🪶',
    color: '#37474f',
    subcategories: [
      'Carrion Crow', 'Hooded Crow', 'Rook', 'Jackdaw',
      'Magpie', 'Jay', 'Raven', 'Chough', 'Other',
    ],
    recipient: 'corvids@bto.org',
  },
  gamebirds: {
    label: 'Game & Doves',
    icon: '🐓',
    color: '#5d4037',
    subcategories: [
      'Pheasant', 'Red-legged Partridge', 'Grey Partridge',
      'Red Grouse', 'Black Grouse', 'Capercaillie', 'Ptarmigan',
      'Woodpigeon', 'Stock Dove', 'Rock Dove', 'Collared Dove', 'Turtle Dove',
      'Other',
    ],
    recipient: 'gamebirds@bto.org',
  },
}

export const getCategoryConfig = (key) => CATEGORIES[key] || CATEGORIES.songbirds
